// <auto-generated />
namespace Orca_Gamma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialremote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialremote));
        
        string IMigrationMetadata.Id
        {
            get { return "201702031827124_initial-remote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
